# Generated by Django 5.1.3 on 2025-04-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_myuser_groups_myuser_is_staff_myuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'User'},
        ),
    ]
