# Generated by Django 5.1.3 on 2025-04-25 06:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0002_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
